// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cizizgvcgclxafvunejg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpeml6Z3ZjZ2NseGFmdnVuZWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNDc3ODAsImV4cCI6MjA1MTcyMzc4MH0.h_X5NuwnoOkpVR1sbvB1dc-8S2IhCmVovTlfjo7ShwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);